name: 'news_push'

on:
  push:
  schedule:
    - cron: '0 22 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        presist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Run my script
      run: |
        python ./my_script.py





    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 来自onlyourmiracle的news每日通知快送 
        
        body: file://text.html
        to: ${{ secrets.MAIL_LIST }}
        from: GitHub Actions
        content_type: text/html

    - name: commit
      run: |
        git config --global user.email 2440310664@qq.com
        git config --global user.name onlyourmiracle
        git add .
        git commit -m "update" -a
    

